# Generated by Django 3.2.9 on 2021-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dog_info_places_product_trainer_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='Close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='places',
            name='Open_time',
            field=models.TimeField(),
        ),
    ]
