# Generated by Django 3.2.9 on 2021-11-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_breed_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Expiry_date',
        ),
    ]
