# Generated by Django 4.0.1 on 2022-03-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='Services',
            new_name='Address',
        ),
    ]
