# Generated by Django 4.1.dev20211110052136 on 2022-04-03 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_breed_info_link_places_link_product_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog_info',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
